export const educationalKeywords = [
    // General Educational Terms
    "education",
    "learning",
    "tutorial",
    "lesson",
    "knowledge",
    "study",
    "class",
    "exam",
    "test",
    "school",
    "university",
    "college",
    "homework",
    "lecture",
    "training",
  
    // 📐 Mathematics
    "math",
    "maths",
    "mathematics",
    "algebra",
    "geometry",
    "calculus",
    "trigonometry",
    "statistics",
    "probability",
    "arithmetic",
    "fractions",
    "equations",
    "functions",
    "derivatives",
    "integrals",
  
    // 📚 English & Language Arts
    "english",
    "grammar",
    "vocabulary",
    "literature",
    "reading",
    "writing",
    "poetry",
    "essay",
    "phonics",
    "comprehension",
    "spelling",
    "linguistics",
    "punctuation",
    "syntax",
    "figurative language",
  
    // 🔬 Science
    "science",
    "biology",
    "physics",
    "chemistry",
    "botany",
    "zoology",
    "astronomy",
    "genetics",
    "microbiology",
    "ecology",
    "anatomy",
    "geology",
    "earth science",
    "molecular biology",
  
    // 💻 Programming & Computer Science
    "programming",
    "coding",
    "computer science",
    "software development",
    "python",
    "javascript",
    "html",
    "css",
    "java",
    "c++",
    "c#",
    "react",
    "node.js",
    "typescript",
    "sql",
    "data structures",
    "algorithms",
    "machine learning",
    "cybersecurity",
    "artificial intelligence",
    "robotics",
    "cloud computing",
  
    // 🔐 Ethical Hacking & Cybersecurity
    "ethical hacking",
    "hacking",
    "cybersecurity",
    "penetration testing",
    "network security",
    "malware analysis",
    "digital forensics",
    "red teaming",
    "blue teaming",
    "security operations",
    "hacking tools",
    "ethical hacker",
    "cryptography",
    "reverse engineering",
  
    // 📊 Data Analysis & AI
    "data analyst",
    "data analysis",
    "data science",
    "big data",
    "data visualization",
    "data mining",
    "data processing",
    "data engineering",
    "business intelligence",
    "data wrangling",
    "sql",
    "excel",
    "tableau",
    "power bi",
    "r programming",
    "deep learning",
    "artificial intelligence",
    "predictive analytics"
  ];
  